-- RETIRED: do not apply this file.
--
-- e-Likha now uses Supabase Auth's direct recovery email OTP flow. Password
-- resets no longer create database requests or require administrator approval.
--
-- Existing installations must keep historical request rows and apply the
-- reviewed migration below to retire the old browser-facing table/RPC access:
--
--   supabase/migrations/20260813125601_retire_password_reset_approvals.sql
--
-- This intentionally contains no executable SQL so running an old setup list
-- cannot recreate or re-grant the removed approval workflow.
