import React, { act } from 'react';
import { createRoot } from 'react-dom/client';
import BulkUserUpload from './BulkUserUpload';
import { readBulkUserFile } from '../../../utils/bulkUsers';
import { createPlatformUsersBatch } from '../../../services/adminApi';
jest.mock('../../../services/adminApi', () => ({createPlatformUsersBatch:jest.fn()}));
jest.mock('../../../utils/bulkUsers', () => ({readBulkUserFile:jest.fn(),bulkResultsCsv:jest.fn()}));

test('upload only previews, confirmation sends student class and hides passwords', async () => {
  global.IS_REACT_ACT_ENVIRONMENT = true;
  HTMLDialogElement.prototype.showModal = jest.fn();
  const container = document.createElement('div'); document.body.appendChild(container);
  const root = createRoot(container);
  const close = jest.fn(), complete = jest.fn();
  const row = {rowNumber:2,name:'Example Student',email:'s@example.com',password:'never-visible-123',role:'student',classId:'',status:'Ready',message:''};
  readBulkUserFile.mockResolvedValue([row, {...row,rowNumber:3,role:'teacher',name:'Teacher',email:'t@example.com'}]);
  createPlatformUsersBatch.mockResolvedValue([{index:0,status:'Created',message:'Enrolled'},{index:1,status:'Created',message:'Created'}]);
  await act(async () => root.render(<BulkUserUpload users={[]} classes={[{id:'class-a',name:'Grade 1',section:'Blue'}]} onClose={close} onComplete={complete} />));
  const input = document.querySelector('input[type=file]');
  Object.defineProperty(input,'files',{value:[new File([''], 'users.csv')],configurable:true});
  await act(async () => input.dispatchEvent(new Event('change',{bubbles:true})));
  expect(createPlatformUsersBatch).not.toHaveBeenCalled();
  expect(document.body.textContent).not.toContain('never-visible-123');
  expect(document.querySelectorAll('select')).toHaveLength(1);
  expect([...document.querySelectorAll('tbody tr')].map((tr) => tr.cells[0].textContent)).toEqual(['1', '2']);
  const templates = [...document.querySelectorAll('.bulk-template-button')];
  expect(templates).toHaveLength(2);
  expect(templates.every((a) => a.hasAttribute('download'))).toBe(true);
  const select = document.querySelector('select');
  await act(async () => {select.value='class-a';select.dispatchEvent(new Event('change',{bubbles:true}));});
  const confirm = [...document.querySelectorAll('button')].find((b) => b.textContent.includes('Confirm & Add 2'));
  await act(async () => confirm.click());
  expect(createPlatformUsersBatch.mock.calls[0][0][0].classId).toBe('class-a');
  expect(createPlatformUsersBatch.mock.calls[0][0][1].classId).toBe('');
  expect(complete).toHaveBeenCalledTimes(1);
  expect(document.body.textContent).toContain('Upload results');
  await act(async () => root.unmount()); container.remove();
  delete global.IS_REACT_ACT_ENVIRONMENT;
});
